<?
$url_site = 'www.easybet.me';
$site = '<strong>easyBet.me</strong>';
$date = '01-01-2024';
?>
<div class="legal">
<p>Le pr&eacute;sent r&eacute;glement (mis &agrave; jour le <?=$date;?>) a pour but de fixer les conditions g&eacute;n&eacute;rales d'utilisation des services propos&eacute;s aux utilisateurs ainsi qu'aux membres titulaires d'un compte sur <?=$site;?>.</p>
<div class="pt20">
<h2 class="h3">Article I - G&eacute;n&eacute;ralit&eacute;s</h2>
<h3 class="h4">1.1 - Organisateur</h3>
Le site Internet <?=$site;?> (<?=$url_site;?>) est &eacute;dit&eacute; par MonWebPro.com&nbsp;<a href="https://www.solimiam.com/legal/">(Voir mentions l&eacute;gales)</a>.<br />MonWebPro.com sera ci apr&egrave;s d&eacute;nomm&eacute;e "L'organisateur".
<h3 class="h4">1.2 - Service propos&eacute;</h3>
<?=$site;?> offre, &agrave; toute personne physique ayant cr&eacute;&eacute; un compte-joueur (sur le site <?=$url_site;?>, l'acc&egrave;s &agrave; sa plateforme de jeu en ligne propri&eacute;t&eacute; exclusive de l'organisateur. Les personnes ayant cr&eacute;&eacute; un compte-joueur seront ci apr&egrave;s d&eacute;nomm&eacute;s "les membres".<br /><br />
<h2 class="h3">Article II - Participation</h2>
<h3 class="h4">2.1: Acc&egrave;s</h3>
Le site <?=$site;?> et les jeux propos&eacute;s sont accessible uniquement par Internet &agrave; l'adresse <?=$url_site;?>. Toute participation doit se faire uniquement sur Internet, &agrave; l'exclusion de tout autre moyen; notamment toute participation par voie postale est exclue.<br />
<h3 class="h4">2.2 - Conditions de participation</h3>
<?=$site;?> est ouvert &agrave; toute personne physique majeure r&eacute;sidant en France m&eacute;tropolitaine, en Belgique, au Luxembourg et en Suisse, except&eacute; le personnel de l'organisateur. La participation au jeu implique l'acceptation sans r&eacute;serve du pr&eacute;sent R&egrave;glement. L'organisateur tranchera souverainement tout litige relatif au jeu et &agrave; son r&egrave;glement. Il ne sera r&eacute;pondu &agrave; aucune demande t&eacute;l&eacute;phonique concernant l'interpr&eacute;tation ou l'application du pr&eacute;sent r&egrave;glement, les m&eacute;canismes ou les modalit&eacute;s du jeu et sur la liste des gagnants. En participant au jeu, le joueur certifie satisfaire toutes les conditions n&eacute;cessaires pour jouer au jeu et s'engage &agrave; utiliser le site en respectant les conditions du pr&eacute;sent r&egrave;glement. Le non respect dudit r&egrave;glement entra&icirc;ne l'annulation automatique de la participation et de l'attribution &eacute;ventuelle de gratifications. Le participant sera amen&eacute; &agrave; s'inscrire en cr&eacute;ant un compte-joueur. En cas de victoire d'un membre, des informations compl&eacute;mentaires permettant son identification et la remise de lots peuvent lui &ecirc;tre demand&eacute;es (civilit&eacute;, nom, pr&eacute;nom, adresse e-mail valide, date de naissance, code postal,...).&nbsp;Le joueur est inform&eacute; et accepte que les informations saisies dans le formulaire d'inscription fassent foi pour &eacute;tablir la preuve de son identit&eacute;. Les informations saisies par le participant l'engagent d&egrave;s leur validation. Le joueur s'engage &agrave; compl&eacute;ter de bonne foi le formulaire d'inscription mis &agrave; sa disposition et &agrave; transmettre &agrave; l'organisateur des informations exactes. Le joueur doit renseigner l'ensemble des zones de saisie, except&eacute;es celles mentionn&eacute;es comme n'&eacute;tant pas obligatoires. Toute inscription inexacte ou incompl&egrave;te ne sera pas prise en compte et entra&icirc;nera la nullit&eacute; de la participation. Les joueurs ne pouvant pas fournir leurs coordonn&eacute;es et identit&eacute; compl&egrave;tes, ou qui les auront fournies de mani&egrave;re inexacte ou mensong&egrave;re seront disqualifi&eacute;s.
<h3 class="h4">2.3 - Participants des mineurs</h3>
Pour participer, les mineurs devront &ecirc;tre munis d'une autorisation &eacute;crite des parents et/ou du tuteur l&eacute;gal communicable &agrave; premi&egrave;re demande de l'organisateur. L'organisateur se r&eacute;serve le droit de demander cette autorisation et de disqualifier tout participant en l'absence de justification.
<h3 class="h4">2.4 - Fraude</h3>
Toute participation doit &ecirc;tre loyale. Il est rigoureusement interdit, par quelque proc&eacute;d&eacute; que ce soit, de modifier ou de tenter de modifier les dispositifs de jeux propos&eacute;s, notamment afin d'en modifier les r&eacute;sultats ou tout &eacute;l&eacute;ment d&eacute;terminant l'issue d'une partie ainsi que les gagnants d'une partie. Toute utilisation de programmes informatiques d&eacute;stin&eacute;s &agrave; jouer &agrave; la place du joueur est rigoureusement interdite. L'organisateur se r&eacute;serve le droit de faire respecter l'&eacute;galit&eacute; de chance entre tous les joueurs, par tous moyens &agrave; sa convenance.<br /><br />
<h2 class="h3">Article III - Principe et fonctionnement</h2>
<h3 class="h4">3.1 - Principe du jeu</h3>
<?=$site;?> est un jeu de solitaire en ligne. Pour participer, le joueur doit &ecirc;tre inscrit (gratuitement) sur le site <?=$site;?> (<?=$url_site;?>) et avoir rempli, lors de son inscription, ses informations personnelles dont il garanti l'authenticit&eacute;.
<h3 class="h4">3.2 - D&eacute;roulement d'une partie</h3>
Lors de l'inscription, les membres de <?=$site;?> ont droit &agrave; un certain nombre de parties gratuites. Ce nombre peut varier en fonction da la saison ou de promotions ponctuelles. Pour jouer davantage, apr&egrave;s &eacute;coulement des cr&eacute;dits, le membre devra tenter de gagner plus de cr&eacute;dits ou en acheter sur le site.</div>
<div class="pt20">&nbsp;</div>
<div class="pt20">Les membres sont invit&eacute;s a effectuer un pronostic par jour sur une s&eacute;lection d'&eacute;v&eacute;nements (sportifs, politique, etc...). Il est possible de jouer jusqu'&agrave; la derni&egrave;re minute avant le d&eacute;but de l'&eacute;v&eacute;nement. La liste des &eacute;v&eacute;nements sur le site est mise &agrave; jour automatiquement en fonction de la date et de l'heure.&nbsp;</div>
<div class="pt20">&nbsp;</div>
<div class="pt20">Un cr&eacute;dit est d&eacute;compt&eacute; apr&egrave;s chaque partie.</div>
<div class="pt20">
<h3 class="h4">3.3 - Modification des lots</h3>
Les lots sont d&eacute;finis par p&eacute;riode, en fonction de la disponibilit&eacute;.<br />
<h3 class="h4">3.4 - Paiement et achat de cr&eacute;dits</h3>
L'achat de cr&eacute;dit se fait via paiement s&eacute;curis&eacute; par carte bancaire avec PayPal. Les tarifs sont indiqu&eacute;s sur le site <?=$site;?>. L'organisateur se r&eacute;serve le droit de modifier ces tarifs &agrave; tout moment sans pr&eacute;avis.<br />
<h3 class="h4">3.5 - Attribution des points</h3>
Chaque jour, les membres peuvent faire un pronostic: il s'agit de tenter de deviner le score ou l'issue du match (victoire d'une &eacute;quipe ou match nul).</div>
<div class="pt20">&nbsp;</div>
<div class="pt20">En cas de score exact, 3 points sont attribu&eacute;s. Si l'issu du match est exact, 1 seul point est attribu&eacute;.&nbsp;</div>
<div class="pt20">&nbsp;</div>
<div class="pt20">Le nombre de points d&eacute;termine la position d'un membre au classement g&eacute;n&eacute;ral.&nbsp;<br />
<h2 class="h3">Article IV - Gains et envoi des lots</h2>
<h3 class="h4">4.1 - Valeur des lots</h3>
Diff&eacute;rents lots peuvent &ecirc;tre mis en jeu sur le site <?=$url_site;?>.&nbsp;</div>
<div class="pt20">La valeur des lots peuvent varier en fonction de la saison, de la disponibilit&eacute; de certains produits, ou provenir de partenaires,...</div>
<div class="pt20"><br />Il ne pourra &ecirc;tre demand&eacute; aucune contre-valeur des dotations pr&eacute;vues aux pr&eacute;sentes, en esp&egrave;ce ou sous toute autre forme, ni un quelconque &eacute;change. L'organisateur se r&eacute;serve le droit d'augmenter ou de dminiuer, &agrave; tout moment, le nombre d'articles mis en jeux, sans pr&eacute;avis ni justification. Les prix seront accept&eacute;s tels qu'ils sont annonc&eacute;s. Aucun changement (de date, de prix) pour quelque raison que ce soit ne pourra &ecirc;tre demand&eacute; par les gagnants. Aucune contrepartie ou &eacute;quivalent financier des gains ne pourra &ecirc;tre demand&eacute; par les gagnants. L'organisateur ne fournira aucune prestation ni garantie, les gains consistant uniquement en la remise des prix pr&eacute;vus ci-dessus.
<h3 class="h4">4.2 - Attribution des lots</h3>
</div>
<div class="pt20">Les lots sont disponibles et affich&eacute;s sur le site durant une p&eacute;riode donn&eacute;e . Les lots sont attribu&eacute;s en fonction de la position des joueurs au classement g&eacute;n&eacute;ral sur le site.</div>
<div class="pt20">Une fois les lots attribu&eacute;s, de nouveaux et une nouvelle p&eacute;riode sont d&eacute;finis.
<h3 class="h4">4.3 - Conditions d'obtention des lots</h3>
Sur demande de l'organisateur, le joueur doit pouvoir justifier de son identit&eacute; en fournissant (par voie postale ou &eacute;lectronique) une photocopie de pi&egrave;ce d'identit&eacute; (photocopie recto/verso d'une carte d'identit&eacute; en cours de validit&eacute; ou d'un passeport en cours de validit&eacute;). Dans un souci d'acheminement des cadeaux, sur demande de l'organisateur, le joueur doit &ecirc;tre en mesure de fourni un justificatif de domicile (facture de t&eacute;l&eacute;phone fixe ou Internet, d'&eacute;lectricit&eacute; ou de gaz) datant de moins de 6 (six) mois. Dans le cas o&ugrave; les donn&eacute;es personnelles communiqu&eacute;es par le joueur sont fausses (de fa&ccedil;on volontaire ou non), l'attribution du lot serait frapp&eacute; imm&eacute;diatement de nullit&eacute;.
<h3 class="h4">4.4 - Livraison</h3>
Chaque lot est envoy&eacute; aux coordonn&eacute;es du joueur gagnant. Les coordonn&eacute;es utilis&eacute;es peuvent&ecirc;tre demand&eacute;es aux joueurs si un envoi postal est n&eacute;cessaire. Les lots seront adress&eacute;s aux gagnants par voie postale ou &eacute;lectronique. L'organisateur s'engage &agrave; adresser par courrier ou tout autre moyen &agrave; sa disposition, au plus tard 60 jours apr&egrave;s un succ&egrave;s, sauf en cas de force majeure ind&eacute;pendant de sa volont&eacute; (rupture de stock par exemple), le gain, aux coordonn&eacute;es indiqu&eacute;es par le membre lors de son inscription sur le site. Les d&eacute;lais de livraison sont variables et ne d&eacute;pendent aucunement de l'organisateur. L'organisateur ne pourra en aucun cas &ecirc;tre tenue pour responsable en cas de perte et de d&eacute;t&eacute;rioration du lot par La Poste et/ou en cas de fonctionnement d&eacute;fectueux des services de La Poste.
<h3 class="h4">4.5 - Responsabilit&eacute;s</h3>
Si pour des raisons ind&eacute;pendante de l'organisateur, un article n'&eacute;tait plus disponible, l'organisateur s'engage &agrave; faire parvenir au joueur gagnant un article de prix &eacute;quivalent. L'organisateur se r&eacute;serve le droit de modifier, sans aucun pr&eacute;avis, la teneur des gains propos&eacute;s. A chacune de ces modifications, l'organisateur avertira les membres des changements effectu&eacute;s. L'organisateur se d&eacute;gage de toute responsabilit&eacute; quant aux conditions de transport des lots par voie postale, et ne pourra &ecirc;tre tenu pour responsable en cas de d&eacute;terioration du mat&eacute;riel ou de perte au cours de son acheminement. Le cadeau est consid&eacute;r&eacute; comme bien re&ccedil;u par le gagnant si celui-ci ne se manifeste pas dans les 14 (quatorze) jours qui suivent l'envoi du cadeau. Les cadeaux gagn&eacute;s ne sont ni &eacute;chang&eacute;s ni rembours&eacute;s par l'organisateur m&ecirc;me en cas de d&eacute;faut.
<h3 class="h4">4.6 - Donn&eacute;es indispensables</h3>
Les lots seront envoy&eacute;s au gagnant uniquement si celui-ci a fourni les informations indispensables pour la livraison (sur demande pr&eacute;alable de l'organisateur); &agrave; savoir: nom et pr&eacute;nom, adresse postale, code postal, ville, pays, et num&eacute;ro de t&eacute;l&eacute;phone de livraison (communiqu&eacute; au livreur pour pouvoir effectuer la livraison).
<h3 class="h4">4.7 - Confirmation aupr&egrave;s du gagnant</h3>
Lorsque de l'attribution des lots, l'organisateur enverra un message de confirmation aux gagants sur l'adresse email qui aura &eacute;t&eacute; indiqu&eacute;e lors de l'inscription. Ce message, en plus de signaler au gagnant qu'un lot lui a &eacute;t&eacute; attribu&eacute;, l'invitera &agrave; confirmer de fa&ccedil;on pr&eacute;cise ses coordonn&eacute;es postales si un envoi postal est n&eacute;cessaire. En cas d'absence de l'ensemble des coordonn&eacute;es n&eacute;cessaire (voir 4.6 - Donn&eacute;es indispensables) et sans r&eacute;ponse &agrave; ce message de la part du gagnant dans les 15 jours qui suivent l'envoie de ce message de confirmation, le lot sera consid&eacute;r&eacute; comme perdu et le gagnant ne sera plus en mesure de r&eacute;clamer son gain. L'organisateur pourra d&eacute;signer un autre gagnant ou remettre le lot en jeu.&nbsp;<br />
<h2 class="h3">Article V - Remboursements</h2>
<h3 class="h4">5.1 - Frais pris en compte</h3>
<?=$site;?> propose des jeux gratuits et sans obligation d'achat. Les joueurs peuvent demander le remboursement des cr&eacute;dits disponibles par email (voir adresse dans les mentions l&eacute;gales). Le montant &agrave; rembourser sera d&eacute;fini par l'organisateur au proratat du montant investit et du nombre de cr&eacute;dits disponibles.&nbsp;
<h3 class="h4">5.2 - Conditions</h3>
Le remboursement est effectu&eacute; sur la base d'une demande et en fonction des cr&eacute;dits disponibles. Pour obtenir le remboursement, le membre devra adresser un courriel &agrave; l'adresse de l'ogranisateur (article 1.1), en pr&eacute;cisant ses nom, pr&eacute;nom et adresse email, sous laquelle le participant s'est inscrit.&nbsp;
<h3 class="h4">5.3 - Documents &agrave; fournir</h3>
La demande de remboursement devra imp&eacute;rativement &ecirc;tre accompagn&eacute;e des pi&egrave;ces suivantes : un RIB, une photocopie de la carte d'identit&eacute;, une photocopie d'un justificatif de domicile. Toute demande incompl&egrave;te ou erron&eacute;e ne pourra &ecirc;tre prise en compte. Lorsque le joueur souhaite &ecirc;tre rembours&eacute; pour plusieurs participations, il doit envoyer des demandes de remboursement s&eacute;par&eacute;es.&nbsp;
<h3 class="h4">6.4 - Exceptions</h3>
Mis &agrave; part les cas de remboursement cit&eacute;s pr&eacute;c&eacute;demment, nul joueur ne peut pr&eacute;tendre &agrave; quelconque remboursement de ses achats sur le site <?=$url_site;?>.<br /><br />
<h2 class="h3">Article VI - Informations personnelles</h2>
<h3 class="h4">6.1 - Droit d'acc&egrave;s</h3>
Les membres autorisent l'utilisation des informations recueillies sur eux, en vue de l'&eacute;tablissement d'un fichier commercial par l'organisateur. En application de la loi Informatique et Libert&eacute;s du 6 Janvier 1978, art L.27, les participants disposent d'un droit d'acc&egrave;s, de rectification et de suppression aux donn&eacute;es les concernant. Les membres (ainsi que leurs parents ou tuteur l&eacute;gal s'ils sont mineurs) peuvent exercer ce droit, ou s'opposer &agrave; ce que les dites donn&eacute;es soient c&eacute;d&eacute;es &agrave; des tiers par demande &eacute;crite adress&eacute;e &agrave; l'organisateur ou via le formulaire contact en ligne sur le site <?=$url_site;?>.
<h3 class="h4">6.2 - Publications</h3>
Du seul fait de l'acceptation de leur prix, les gagnants autorisent l'utilisation de leur nom, pr&eacute;nom, adresse email et pseudonyme dans toute manifestation publicitaire li&eacute;e au pr&eacute;sent jeu, sans limitation d'espace ou de temps et sans que cette utilisation puisse ouvrir d'autres droits que le prix gagn&eacute;.<br /><br />
<h2 class="h3">Article VII - Responsabilit&eacute;s</h2>
<h3 class="h4">7.1 - Limites de l'organisateur</h3>
La responsabilit&eacute; de l'organisateur ne pourra en aucun cas &ecirc;tre engag&eacute;e en cas d'&eacute;ventuel dysfonctionnement du mode de participation au pr&eacute;sent jeu, li&eacute; aux caract&eacute;ristiques m&ecirc;me de l'Internet, dans ce cas les participants ne pourront pr&eacute;tendre &agrave; aucune contrepartie de quelque nature que ce soit. L'organisateur ne garantit pas que les sites qu&rsquo;il exploite fonctionnent sans interruption ou qu'ils ne contiennent pas d'erreurs informatiques quelconques, ni que les d&eacute;fauts constat&eacute;s seront corrig&eacute;s. L'organisateur ne saurait &ecirc;tre tenu responsable, si pour une raison ind&eacute;pendante de sa volont&eacute;, le gagnant ne pourrait &ecirc;tre joint. L'organisateur ne peut &ecirc;tre tenu responsable si, pour des raisons de force majeures ind&eacute;pendantes de sa volont&eacute;, le pr&eacute;sent jeu &eacute;tait partiellement ou totalement modifi&eacute;, report&eacute; ou annul&eacute;. Aucune contre-valeur des gratifications mises en jeu ne sera offerte en compensation. L'organisateur ne pourrait &ecirc;tre tenu responsable si les donn&eacute;es relatives &agrave; l'inscription d'un participant ne lui parvenaient pas pour une quelconque raison dont il ne pourrait &ecirc;tre tenue responsable ou lui arrivaient illisibles ou impossibles &agrave; traiter. Plus g&eacute;n&eacute;ralement, s'agissant d'un jeu gratuit et sans aucune obligation d'achat, il est express&eacute;ment convenu, en application de l'article 1152 du code civil, que la responsabilit&eacute; de l'organisateur serait limit&eacute;e - si elle venait &agrave; &ecirc;tre recherch&eacute;e - &agrave; une somme forfaitaire comprise entre un euro et la valeur commerciale moyenne de la plus haute gratification mise en jeu sur le site <?=$site;?>.
<h3 class="h4">7.2 - Reponsabilit&eacute; des joueurs</h3>
La connexion de toute personne au site et la participation des membres aux jeux propos&eacute;s sur le site se fait sous leur enti&egrave;re responsabilit&eacute;. Il appartient &agrave; tout participant de prendre toutes les mesures appropri&eacute;es de fa&ccedil;on &agrave; prot&eacute;ger ses propres donn&eacute;es et/ou logiciels stock&eacute;s sur son &eacute;quipement informatique contre toute atteinte. Par ailleurs, l'organisateur ne saurait naturellement avoir aucune responsabilit&eacute; relative aux difficult&eacute;s ou impossibilit&eacute;s de connexions des participants &agrave; Internet.
<h3 class="h4">7.3 - Fraude</h3>
Toute fraude, ou tentative de fraude, manifest&eacute;e par un commencement d'ex&eacute;cution et commise notamment en vue de percevoir ind&ucirc;ment un lot, fera l'objet de poursuites p&eacute;nales, conform&eacute;ment aux dispositions des articles 313-1 et suivants du Code P&eacute;nal. Toute atteinte au syst&egrave;me de traitement automatis&eacute; de donn&eacute;es sur <?=$site;?> fera l'objet de poursuites p&eacute;nales, conform&eacute;ment aux dispositions des articles 323-1 &agrave; 323-7 du Code P&eacute;nal. Tout faux et usage de faux fera l'objet de poursuites p&eacute;nales, conform&eacute;ment aux dispositions des articles 441-1 &agrave; 441-12 du Code P&eacute;nal. Toute op&eacute;ration ayant pour objet ou pour effet de porter atteinte au secret des correspondances, au secret professionnel ou aux donn&eacute;es relatives &agrave; la vie priv&eacute;e des joueurs fera l'objet de poursuites, conform&eacute;ment aux dispositions civiles et p&eacute;nales en vigueur. En cas de non respect ou de pr&eacute;somption de non respect du pr&eacute;sent r&egrave;glement par un joueur ou en cas d'infraction, de tentative ou de pr&eacute;somption d'infraction de la part d'un joueur susceptible de faire l'objet de poursuites, conform&eacute;ment aux dispositions du pr&eacute;sent article, l'organisateur pourra interdire temporairement, voire d&eacute;finitivement, l'acc&egrave;s de ce membre &agrave; son compte joueur. Il est rappel&eacute; que l'usage frauduleux du num&eacute;ro de carte bancaire d'une autre personne sans son consentement constitue juridiquement un d&eacute;lit d'escroquerie r&eacute;prim&eacute; par l'article 313.1 du code p&eacute;nal par une peine de 5 ans d'emprisonnement et 382 000 &euro; d'amende. Le fait d'utiliser sa carte bleue pour acheter des cr&eacute;dits et de se d&eacute;dire constitue &eacute;galement un d&eacute;lit.
<h3 class="h4">7.4 - Force majeur</h3>
L'organisateur se r&eacute;serve le droit d'exclure tout joueur qu'il soup&ccedil;onnerait de triche/fraude, et &eacute;galement d'annuler tout envoi de cadeau. L'organisateur ne pourra &ecirc;tre tenue pour responsable si, pour une raison ind&eacute;pendante de sa volont&eacute;, un ou plusieurs des jeux ou services venaient &agrave; &ecirc;tre modifi&eacute;(s), report&eacute;(s) ou annul&eacute;(s).
<h3 class="h4">7.5 - Les Services de <?=$site;?></h3>
Le Membre s'interdit de "revendre" ou de mettre &agrave; disposition d'un tiers et/ou des autres Membres, &agrave; titre on&eacute;reux et/ou gratuit, les services propos&eacute;s par <?=$site;?>.
<h3 class="h4">7.6 - Modification du r&eacute;glement</h3>
L'organisateur se r&eacute;serve la possibilit&eacute; d&rsquo;apporter toute modification au r&egrave;glement sans pr&eacute;avis ni obligation de motiver sa d&eacute;cision et sans que sa responsabilit&eacute; ne puisse &ecirc;tre engag&eacute;e de ce fait. L'organisateur se r&eacute;serve la facult&eacute;, &agrave; tout moment, de plein droit sans pr&eacute;avis et sans avoir &agrave; en justifier, d&rsquo;interrompre le jeu, de le proroger, de l&rsquo;&eacute;courter, de le modifier ou de l&rsquo;annuler. En ce cas, la responsabilit&eacute; de l'organisateur ne pourra &ecirc;tre engag&eacute;e d&rsquo;aucune mani&egrave;re de ce fait et les joueurs ne pourraient pr&eacute;tendre &agrave; aucun d&eacute;dommagement d&rsquo;aucune sorte. Toute modification du r&egrave;glement donnera lieu &agrave; un nouveau d&eacute;p&ocirc;t et entrera en vigueur &agrave; compter de sa mise en ligne et tout joueur sera r&eacute;put&eacute; l&rsquo;avoir accept&eacute;e du simple fait de sa participation au jeu, &agrave; compter de la date d&rsquo;entr&eacute;e en vigueur de la modification. Tout joueur refusant la ou les modifications intervenues devra cesser de participer au jeu.<br /><br />
<h2 class="h3">Article VIII - Diverses fonctionnalit&eacute;s du site</h2>
<h3 class="h4">8.1 - Mot de passe et s&eacute;curit&eacute;</h3>
Le mot de passe du membre est personnel et confidentiel. <?=$site;?> ne pourra &ecirc;tre tenu responsable en cas de perte ou de vol. Aucun site n'&eacute;tant prot&eacute;g&eacute; &agrave; 100% sur Internet, <?=$site;?> s'engage &agrave; faire tout son possible pour que la protection soit maximale, cependant <?=$site;?> ne pourra &ecirc;tre tenu responsable en cas de disfonctionnement de ses services, mais s'engage &agrave; mettre tout en oeuvre pour corriger les &eacute;ventuelles failles.
<h3 class="h4">8.3 - Fermeture de compte</h3>
Si un membre d&eacute;sire mettre fin &agrave; son contrat, il devra soit en aviser <?=$site;?> par E-MAIL ou bien en utilisant le formulaire de contact mis &agrave; sa disposition sur le site. L'organisateur s'engage alors &agrave; supprimer le compte du membre dans un d&eacute;lai de 15 jours.<br /><br />
<h2 class="h3">Article IX - Litiges</h2>
<h3 class="h4">9.1 - Preuves</h3>
Dans le cadre de l'organisation des jeux sur le site <?=$site;?>, les fichiers et autres donn&eacute;es informatiques feront seuls foi. Les registres informatis&eacute;s, conserv&eacute;s dans les syst&egrave;mes informatiques du site <?=$url_site;?>, dans des conditions raisonnables de s&eacute;curit&eacute; et de fiabilit&eacute;, sont consid&eacute;r&eacute;s comme les preuves des relations et communications intervenues entre le site <?=$url_site;?> et le participant.
<h3 class="h4">9.2 - Op&eacute;rations non-d&eacute;sir&eacute;es</h3>
Les op&eacute;rations de toute nature r&eacute;alis&eacute;es &agrave; l'aide de l'identifiant et du code attribu&eacute;s &agrave; un participant, &agrave; la suite de l'inscription, sont pr&eacute;sum&eacute;es de mani&egrave;re irr&eacute;fragable, avoir &eacute;t&eacute; r&eacute;alis&eacute;es sous la responsabilit&eacute; du titulaire du compte joueur.
<h3 class="h4">9.3 - Cas non-pr&eacute;vus</h3>
Tous les cas non pr&eacute;vus par le r&egrave;glement seront tranch&eacute;s par l'organisateur dont les d&eacute;cisions seront sans appel.
<h3 class="h4">9.4 - Loi</h3>
La loi qui s'applique au pr&eacute;sent contrat est la loi fran&ccedil;aise. Les joueurs sont donc soumis &agrave; la r&eacute;glementation fran&ccedil;aise applicable aux jeux. Tout litige n&eacute; &agrave; l'occasion d'un jeu pr&eacute;sent sur <?=$site;?>, et qui ne pourra &ecirc;tre r&eacute;gl&eacute; &agrave; l'amiable sera soumis aux juridictions comp&eacute;tentes dont d&eacute;pend le si&egrave;ge social de l'organisateur, sauf dispositions d'ordre public contraires.</div>
<div class="pt20">&nbsp;</div>

<!--
<h2 class="h3">Article X - Parrainage</h2>
<h3 class="h4">10.1 - Principe de fonctionnement</h3>
Est appel&eacute;e "parrain" toute personne physique inscrite sur le site <?=$url_site;?> et amenant de nouveaux joueurs &agrave; s'inscrire alors appel&eacute;s "filleuls". Un nouveau joueur est le filleul d'un autre lorsqu'il s'est inscrit apr&egrave;s avoir cliqu&eacute; sur le lien de parrainage. Tous les joueurs peuvent diffuseur leur lien de parrainage disponible dans la rubrique "Espace membre/ Mes filleuls".<br />
<h3 class="h4">10.2 - Conditions</h3>
Le parrain et les filleuls doivent &ecirc;tre des personnes physiques distinctes. Le parrainage est applicable dans les conditions d&eacute;finies &agrave; l'article 2.2 concernant les conditions de participation. Il est strictement interdit de diffuser un lien de parrainage par quelconque proc&eacute;d&eacute; ill&eacute;gal (spam par exemple). L'organisateur se d&eacute;gage de toute responsabilit&eacute; quant &agrave; l'utilisation faite du lien de parrainage par les joueurs.
<h3 class="h4">10.3 - Outil de diffusion d'invitations</h3>
L'organisateur met &agrave; disposition des joueurs un outil de diffusion d'invitations permettant d'envoyer automatiquement un e-mail d'invitation &agrave; plusieurs personnes. Cet outil est disponible dans la page "Parrainage". L'usage que fera le joueur de cet outil est de son enti&egrave;re responsabilit&eacute;. Le joueur s'engage &agrave; ne contacter des personnes physiques qu'il connait.
<h3 class="h4">10.4 - Gains</h3>
Chaque parrain per&ccedil;oit un certain de nombre de CREDIZ d&egrave;s lors qu'un de ces filleuls remporte un certain nombre de MIAMS. Les filleurs, d&egrave;s leur inscription, se voient cr&eacute;diter d'un certain nombre de CREDIZ.</div>
//-->

<script>
$(document).prop('title', 'Conditions générales de vente - <?php echo $Site['nom']; ?>');
</script>